// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SRC.DiscordBot;
using SRC.DiscordBot.Services;

#nullable disable

namespace SRC.DiscordBot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260731185155_AddNotifiedFlag")]
    partial class AddNotifiedFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("SRC.DiscordBot.DataModels.KoruxaBoss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("HasNotifiedSpawn")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_notified_spawn");

                    b.Property<DateTimeOffset?>("KilledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("killed_at");

                    b.HasKey("Id")
                        .HasName("pk_koruxa_boss");

                    b.ToTable("koruxa_boss", (string)null);
                });

            modelBuilder.Entity("SRC.DiscordBot.DataModels.KoruxaBossAttack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AttackedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("attacked_at");

                    b.Property<int>("BossId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("boss_id");

                    b.Property<ulong>("DiscordUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("discord_user_id");

                    b.HasKey("Id")
                        .HasName("pk_koruxa_boss_attack");

                    b.HasIndex("BossId")
                        .HasDatabaseName("ix_koruxa_boss_attack_boss_id");

                    b.ToTable("koruxa_boss_attack", (string)null);
                });

            modelBuilder.Entity("SRC.DiscordBot.KoruxaUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<ulong>("DiscordUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("discord_user_id");

                    b.Property<DateTimeOffset>("LastAlertSendAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_alert_send_at");

                    b.HasKey("Id")
                        .HasName("pk_koruxa_user");

                    b.HasIndex("DiscordUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_koruxa_user_discord_user_id");

                    b.ToTable("koruxa_user", (string)null);
                });

            modelBuilder.Entity("SRC.DiscordBot.DataModels.KoruxaBossAttack", b =>
                {
                    b.HasOne("SRC.DiscordBot.DataModels.KoruxaBoss", null)
                        .WithMany("Attacks")
                        .HasForeignKey("BossId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_koruxa_boss_attack_koruxa_boss_boss_id");
                });

            modelBuilder.Entity("SRC.DiscordBot.DataModels.KoruxaBoss", b =>
                {
                    b.Navigation("Attacks");
                });
#pragma warning restore 612, 618
        }
    }
}
