<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <OutputType>exe</OutputType>
        <UserSecretsId>65e0f499-8b08-4709-b8fe-7b4f10b7aefb</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="EFCore.NamingConventions" Version="10.0.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.10" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
      <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.10" />
      <PackageReference Include="NetCord.Hosting.Services" Version="1.0.0-beta.11" />
      <PackageReference Include="Nixon.Extensions.EntityFrameworkCore" Version="10.0.8" />
      <PackageReference Include="Nixon.Extensions.Hosting.Jobs" Version="10.0.3" />
      <PackageReference Include="Nixon.Extensions.Serilog.AspNetCore" Version="10.0.15" />
      <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="appsettings.*.json">
            <DependentUpon>appsettings.json</DependentUpon>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    
</Project>
